apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n01714294-final-exam
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/jaihirani2330/n01714294_CCGC5504_FINAL_EXAM
    targetRevision: HEAD
    path: k8s-manifests/helm-chart
    helm:
      valueFiles:
        - values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: n01714294-final-exam
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
